#!/usr/bin/env node
/**
 * Sync the built-in motor database from the upstream community motor list and regenerate
 * src/model/motorDatabase.ts. Run by scripts/update-motors workflow on a schedule; it opens a PR when
 * the generated file changes, so new motors are picked up automatically without hand-editing.
 *
 *   node scripts/update-motors.mjs            # fetch + regenerate
 *   node scripts/update-motors.mjs --check    # exit 1 if the generated file would change (no write)
 *
 * This is dev tooling only (not shipped in the plugin bundle). The generated data file contains motor
 * electrical specs from manufacturer datasheets and carries no third-party branding.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE = "https://raw.githubusercontent.com/andrewmcgr/klipper_tmc_autotune/main/motor_database.cfg";
const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "src", "model", "motorDatabase.ts");

// Tidy verbose source section headings into short manufacturer labels for the picker.
const VENDOR_TIDY = {
	"China Leadshine Technology Co., Ltd Motors (Leisai, Leadshine)": "Leadshine",
	"Trinamic (yes, they also make stepper motors)": "Trinamic",
	"Guangzhou Bozu Digital Technology": "Bozu",
	"OMC Stepperonline": "StepperOnline",
};

function parse(cfg) {
	let vendor = "";
	const entries = [];
	let cur = null;
	const flush = () => { if (cur) { entries.push(cur); cur = null; } };
	for (const raw of cfg.split(/\r?\n/)) {
		const s = raw.trim();
		if (s.startsWith("###")) {
			const m = s.match(/^#+\s*(.+?)\s*#+\s*$/);
			vendor = m ? m[1].replace(/\s*Motors?$/i, "").trim() : vendor;
			continue;
		}
		if (s.startsWith("##")) continue;
		const head = s.match(/^\[motor_constants\s+(.+?)\]\s*$/);
		if (head) { flush(); cur = { id: head[1].trim(), vendor: VENDOR_TIDY[vendor] ?? vendor ?? "Other" }; continue; }
		if (cur) {
			const kv = s.match(/^([a-z_]+)\s*:\s*([-+0-9.eE]+)/);
			if (kv) cur[kv[1]] = Number(kv[2]);
		}
	}
	flush();
	const motors = [];
	for (const e of entries) {
		const r = e.resistance, l = e.inductance, t = e.holding_torque, i = e.max_current;
		const st = e.steps_per_revolution ?? 200;
		if ([r, l, t, i].some((v) => v == null || !Number.isFinite(v))) continue;
		motors.push({ id: e.id, vendor: e.vendor || "Other", resistance: r, inductance: l, holdingTorque: t, maxCurrent: i, stepsPerRev: Math.round(st) });
	}
	return motors;
}

function render(motors) {
	const head = [
		"/**",
		" * Built-in stepper-motor database: electrical specifications compiled from manufacturer",
		" * datasheets. Each entry feeds the autotune engine (see model/autotune.ts). Users can also",
		" * enter a custom motor by hand.",
		" *",
		" * GENERATED by scripts/update-motors.mjs — do not edit by hand.",
		" */",
		"export interface MotorSpec {",
		'\t/** Stable id / catalogue part identifier, e.g. "ldo-42sth48-2504ah". */',
		"\tid: string;",
		'\t/** Manufacturer grouping for the picker, e.g. "LDO", "Moons". */',
		"\tvendor: string;",
		"\t/** Phase (coil) resistance, ohms. */",
		"\tresistance: number;",
		"\t/** Phase (coil) inductance, henries. */",
		"\tinductance: number;",
		"\t/** Holding torque, Nm. */",
		"\tholdingTorque: number;",
		"\t/** Nominal rated (max) phase current, amps. */",
		"\tmaxCurrent: number;",
		"\t/** Full steps per revolution (200 = 1.8°, 400 = 0.9°). */",
		"\tstepsPerRev: number;",
		"}",
		"",
		`/** ${motors.length} motors, compiled from manufacturer datasheets. */`,
		"export const MOTOR_DATABASE: ReadonlyArray<MotorSpec> = [",
	];
	const rows = motors.map((m) =>
		`\t{ id: ${JSON.stringify(m.id)}, vendor: ${JSON.stringify(m.vendor)}, resistance: ${m.resistance}, ` +
		`inductance: ${m.inductance}, holdingTorque: ${m.holdingTorque}, maxCurrent: ${m.maxCurrent}, stepsPerRev: ${m.stepsPerRev} },`);
	return [...head, ...rows, "];", ""].join("\n");
}

const res = await fetch(SOURCE);
if (!res.ok) {
	console.error(`Failed to fetch motor list: HTTP ${res.status}`);
	process.exit(2);
}
const motors = parse(await res.text());
if (motors.length < 150) {
	console.error(`Refusing to write: only parsed ${motors.length} motors (source format may have changed).`);
	process.exit(2);
}
const next = render(motors);
const current = (() => { try { return readFileSync(OUT, "utf8"); } catch { return ""; } })();

if (next === current) {
	console.log(`Motor database up to date (${motors.length} motors).`);
	process.exit(0);
}

if (process.argv.includes("--check")) {
	console.error(`Motor database is out of date (${motors.length} motors upstream). Run: npm run update-motors`);
	process.exit(1);
}

writeFileSync(OUT, next, "utf8");
console.log(`Wrote ${motors.length} motors to src/model/motorDatabase.ts`);
